### PR TITLE
Fix back button opening modal

### LINKED ISSUE #545: Back arrow opens modal instead of going back to the data-modal view.
grafik

Pressing the arrow should lead back to the main data-model page. When having edited a field the last url becomes the field so instead of going back the field modal opens up again.

### PR DESCRIPTION
**Pull request by Nitwel**
closes #545

### CODE REVIEW

File: app/src/modules/collections/routes/detail.vue [hunk 1]
```diff
@@ -33,7 +33,7 @@
 				secondary
 				exact
 				v-tooltip.bottom="$t('back')"
-				@click="$router.go(-1)"
+				:to="'/collections/'+collection"
```
Comment (rijkvanzanten) [inline app/src/modules/collections/routes/detail.vue:36]:
```suggestion
				:to="'/collections/' + collection"
```

**Review by rijkvanzanten — APPROVED** [review]
